#pragma once

enum WHEEL_TYPE { WHEEL_FL, WHEEL_FR, WHEEL_BL, WHEEL_BR, WHEEL_END };

enum BOOSTER_TYPE { WIND_L1, WIND_R1, WIND_L2, WIND_R2, WIND_END };

enum CART_STATE { CART_STATE_GROUND, CART_STATE_AIR, CART_STATE_LANDING, CART_STATE_END };

enum BOOST_STATE { BOOST_STATE_NORMAL, BOOST_STATE_SHORT_BOOST, BOOST_STATE_LONG_BOOST, BOOST_STATE_END };

enum INVEN_SLOT_NUM { INVEN_FIRST, INVEN_SECOND, INVEN_END };

enum CHAR_TYPE { CHAR_BAZZI, CHAR_DAO, CHAR_END };

enum CHAR_COLOR { COLOR_RED, COLOR_GREEN, COLOR_END };

enum DRIFT_SPARK_TYPE { DRIFT_SPARK_TYPE_LEFT, DRIFT_SPARK_TYPE_RIGHT, DRIFT_SPARK_TYPE_END };

enum RANK_MARK_COLOR { MARK_RED, MARK_BLUE, MARK_GRAY, MARK_YELLOW, MARK_END };

enum RANK_ROW_OWNER { ROW_OWNER_PLAYER, ROW_OWNER_BOT, ROW_OWNER_END };

enum RANK_NAME { NAME_PLAYER, STUPID_BAZZI, SMART_BAZZI, STUPID_DAO, SMART_DAO, STUPID_UNI, SMART_UNI, RANK_NAME_END };

enum WHEEL_TURN { TURN_LEFT, TURN_RIGHT, TURN_END };


enum MAP_ID {
	MAP_ITEM,
	MAP_SPEED,
	MAP_END
};
enum ITEM_TYPE
{
	ITEM_BOOSTER, ITEM_THUNDER, ITEM_CLOUD, ITEM_WATERFLY,
	ITEM_MAGNET, ITEM_BARRICADE, ITEM_ROCKET, ITEM_BANANA, 
	ITEM_WATERBOMB,ITEM_SHIELD,
	ITEM_END
};

enum DIRECTION_TYPE { DIR_FORWARD = 1, DIR_REVERSE = -1 };

enum BACKGROUND { BACKGROUND_LOADING, BACKGRTOUND_NEXON, BACKGROUND_STARTMENU, BACKGROUND_ITEMMENU, BACKGROUND_SETITEMMENU, BACKGROUND_SPEEDMENU, BACKGROUND_SETSPEEDMENU, BACKGROUND_END };

enum AIM_STATE { AIM_NONE, AIM_CLOSE, AIM_TARGET, AIM_END };